apiVersion: v1
kind: Service
metadata:
  name: k8s-network-demo-service
  namespace: k8s-network-demo
spec:
  type: LoadBalancer
  selector:
    app: k8s-network-demo-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
